language: julia
os:
- linux
julia:
- 1
notifications:
  email: false
git:
  depth: 99999999
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
    - PART=1/12
    - PART=2/12
    - PART=3/12
    - PART=4/12
    - PART=5/12
    - PART=6/12
    - PART=7/12
    - PART=8/12
    - PART=9/12
    - PART=10/12
    - PART=11/12
    - PART=12/12
sudo: required
jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder"; Pkg.build()'
script:
- julia --color=yes build_tarballs.jl --part=$PART --verbose
deploy:
  provider: releases
  api_key:
    secure: 4VL0VBEUh1UWc62h/2ya8Yd759jK0OfowuYgl73k4c+T0j9Jj7BxtbwhDLm6Q+Q5dRxQtRPwf0J2tD8TTMVxtuaE/xZ+cLrC6uQO5lnB8T/8Ew5nj0zqGHIp4COiqmJiHgPWQm4nyna+tXcoJHNRZ9aXF6MbqHFG9lpqNjHCq7+oXEtAyTtkwxkI7d+QNLASrKzjr2ChKfcg3GN8TOyEpJ7osxXsXMM8v5W26PD4FWsTkufqp/IM1sT5K1XRcpeUxa4zTLrPZLKy8sMwHnS6lPwJBZtD1tU94Ah1doZJRcO0FF+hDHwV8wvDDNzCXxzBBH5GciVI1wCOw3+ecE8KrfFCSuCmaJv5kEtCRd2cT3l5TPb15QVJW2lQJxlEC5ycHLoVOpoKCpl88xHazUQLII6+z3muT2GwvAGvL39e+hjumRznCDFGURKLX6avVsxz0AOJ7AH13GP+cDY1JpTIgIjkRC73auQ59noYPHT3PQUtK5IEK4+yo1K7Gljd8Dgki6iAGcYIHtptrY0vDQNEcmPAS2JdRLykfvtve3XuXwCv6QA/ANhYHUDPz7bxknTuD4zCG3imngkNxxSP4RMLmvsrQsgyyjlXudOl1tlIJMVMgoMnH6A1HzD0M2JJrGtPckgP2QcS+O08zYFupo7nveh5LlAlBWvE0TEWJsYrzNA=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: GMLC-TDC/HELICSBuilder
    tags: true
