name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-linux-gnu-cxx11
          - x86_64-linux-gnu-cxx11
          - aarch64-linux-gnu-cxx11
          - arm-linux-gnueabihf-cxx11
          - powerpc64le-linux-gnu-cxx11
          - i686-linux-musl-cxx11
          - x86_64-linux-musl-cxx11
          - aarch64-linux-musl-cxx11
          - arm-linux-musleabihf-cxx11
          - x86_64-apple-darwin14-cxx11
          # - x86_64-unknown-freebsd11.1-cxx11
          - i686-w64-mingw32-cxx11
          - x86_64-w64-mingw32-cxx11

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.3.1
      - name: Setup BinaryBuilder
        env:
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: |
          julia --color=yes -e 'using Pkg; pkg"add BinaryBuilder#master; build"'
          julia --color=yes build_tarballs.jl --verbose ${{ matrix.target }}
      - name: Publish tarball
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: products/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
